# Generated by Django 4.2.13 on 2026-05-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit_price', models.FloatField(verbose_name='Unit Price (£)')),
                ('month', models.IntegerField(verbose_name='Month (1-12)')),
                ('day_of_week', models.IntegerField(verbose_name='Day of Week (0=Mon, 6=Sun)')),
                ('hour', models.IntegerField(verbose_name='Hour of Day (0-23)')),
                ('predicted_label', models.CharField(choices=[('high', 'High Value Order'), ('low', 'Low Value Order')], max_length=10, verbose_name='Prediction Result')),
                ('predicted_total', models.FloatField(default=0.0, verbose_name='Estimated Total (£)')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Model Confidence (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20, verbose_name='Invoice Number')),
                ('stock_code', models.CharField(max_length=20, verbose_name='Stock Code')),
                ('description', models.CharField(max_length=300, verbose_name='Product Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity Sold')),
                ('invoice_date', models.DateTimeField(verbose_name='Invoice Date')),
                ('unit_price', models.FloatField(verbose_name='Unit Price (£)')),
                ('customer_id', models.FloatField(blank=True, null=True, verbose_name='Customer ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount (£)')),
            ],
            options={
                'verbose_name': 'Sales Record',
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
